### ISSUE TITLE
missing transformers module

### ISSUE THREAD

**Issue by wideglide** [RazorMegrez/VulHawk#4]
I'm having trouble getting the code working.  It seems like a module is missing from this repository.

```
C:\dev\src\VulHawk>python.exe 2_FileEnvironmentIdentification.py --help
Traceback (most recent call last):
  File "2_FileEnvironmentIdentification.py", line 18, in <module>
    from utils.runtime import EntropyModel, EntropyHead, arch_map
  File "runtime.py", line 5, in init runtime
  File "languageModel.py", line 24, in init languageModel
ModuleNotFoundError: No module named 'transformers'
```

**Comment by wideglide** [comment]
If someone else is having issues, there's several more dependencies not mentioned, AND this only works with Python 3.8 on Windows. 

Here's the extras I had to install:
```
matplotlib
networkx
numpy
scikit-learn
torch               1.13.1+cu116
torch-geometric     2.3.1
torch-scatter       2.1.1+pt113cu116
torch-sparse        0.6.17+pt113cu116
transformers
tqdm
```

**Comment by Solar-Lu** [comment]
how to complete?
